name: hijri
description: >
  Convert between Hijri Calendar and Gregorian Calendar date.
version: 2.0.2
homepage: https://github.com/ahmedoid/hijri_date

environment:
  sdk: '>=2.4.0 <3.0.0'


dev_dependencies:
  test: "^1.14.3"