name: hijri
description: >
  Convert between Hijri and  Gregorian calendar days.
version: 1.0.1
homepage: https://github.com/ahmedoid/hijri_date

environment:
  sdk: '>=2.4.0 <3.0.0'


dev_dependencies:
  test: "^1.14.3"